apiVersion: apps/v1
kind: Deployment
metadata:
  name: wep-page
  namespace: webapp
  labels:
    app: wep-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wep-page
  template:
    metadata:
      labels:
        app: wep-page
    spec:
      containers:
      - name: wep-page
        image: fettahogluhande/wep-page:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wep-page-service
  namespace: webapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wep-page
---
apiVersion: v1
kind: Ingress
metadata:
  name: wep-page-ingress
  namespace: webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webapp.anka.local  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wep-page-service
            port:
              number: 80
