apiVersion: apps/v1
kind: Deployment
metadata:
  name: wep-page
  namespace: jenkins
  labels:
    app: wep-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wep-page
  template:
    metadata:
      labels:
        app: wep-page
    spec:
      containers:
      - name: wep-page
        image: fettahogluhande/wep-page:${BUILD_ID}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wep-page-service
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: wep-page
